In [2]:
from __future__ import absolute_import, division, print_function
import numpy as np
import pandas as pd
import tensorflow as tf
tf.enable_eager_execution()

In [41]:
import requests
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.dates as mdates

In [ ]:
x = np.array()
y = )
z = tf

In [5]:
x = np.array([[2.]])
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


In [20]:
klines = requests.get('https://www.binance.com/api/v1/klines?symbol=XRPBTC&interval=5m&limit=100').json()

In [21]:
df = pd.DataFrame(klines, columns=["time", "open", "high", "low", "close", "volume", "ctime", "qvolume", "trades", "tbbav", "tbqav", "ig"])

In [35]:
prices = np.array(df[["close"]].values).astype(np.float)

In [36]:
y = prices[1:] # skips first
x = prices[:-1] # skips last

In [39]:
delta = y-x

In [95]:
actions_long = np.expand_dims(np.random.uniform(low=0, high=1, size=99), axis=1)
actions_short = np.expand_dims(np.random.uniform(low=0, high=1, size=99), axis=1)

In [96]:
actions = np.concatenate((actions_long,actions_short),axis=1)

In [109]:
pv_actions = actions/np.expand_dims(np.sum(actions, axis=1), axis=1)

In [114]:
pv_actions = np.prod([pv_actions, [1,-1]])

In [117]:
delta

array([[ 2.9e-07],
       [-1.5e-07],
       [ 1.0e-08],
       [ 4.0e-08],
       [ 3.0e-08],
       [ 3.0e-08],
       [-1.5e-07],
       [ 0.0e+00],
       [ 8.0e-08],
       [ 3.0e-08],
       [-7.0e-08],
       [ 3.0e-08],
       [ 5.0e-08],
       [ 6.0e-08],
       [ 1.0e-08],
       [-1.8e-07],
       [ 1.8e-07],
       [ 6.0e-08],
       [ 5.2e-07],
       [ 7.7e-07],
       [-5.5e-07],
       [-2.0e-08],
       [-3.0e-08],
       [ 1.4e-07],
       [-2.7e-07],
       [ 1.4e-07],
       [-9.0e-08],
       [-8.0e-08],
       [ 9.0e-08],
       [ 2.0e-07],
       [ 1.0e-07],
       [ 3.2e-07],
       [ 2.1e-07],
       [-2.1e-07],
       [ 1.2e-07],
       [ 8.3e-07],
       [ 5.6e-07],
       [-6.1e-07],
       [-8.9e-07],
       [-2.9e-07],
       [ 1.9e-07],
       [-3.5e-07],
       [ 7.0e-08],
       [ 1.8e-07],
       [-2.4e-07],
       [ 1.9e-07],
       [-1.2e-07],
       [ 2.1e-07],
       [-1.2e-07],
       [-2.1e-07],
       [-4.0e-08],
       [ 1.9e-07],
       [ 3.0

In [116]:
pv_actions

array([[ 0.43998114, -0.56001886],
       [ 0.92583242, -0.07416758],
       [ 0.52419395, -0.47580605],
       [ 0.68781779, -0.31218221],
       [ 0.50554314, -0.49445686],
       [ 0.74476205, -0.25523795],
       [ 0.88631525, -0.11368475],
       [ 0.55600804, -0.44399196],
       [ 0.45914876, -0.54085124],
       [ 0.15442359, -0.84557641],
       [ 0.21582093, -0.78417907],
       [ 0.67815424, -0.32184576],
       [ 0.41689635, -0.58310365],
       [ 0.19079491, -0.80920509],
       [ 0.448938  , -0.551062  ],
       [ 0.20117546, -0.79882454],
       [ 0.50348207, -0.49651793],
       [ 0.35275214, -0.64724786],
       [ 0.70007155, -0.29992845],
       [ 0.66250763, -0.33749237],
       [ 0.51103873, -0.48896127],
       [ 0.72608513, -0.27391487],
       [ 0.53002809, -0.46997191],
       [ 0.5163256 , -0.4836744 ],
       [ 0.43112014, -0.56887986],
       [ 0.11443374, -0.88556626],
       [ 0.36254269, -0.63745731],
       [ 0.62983538, -0.37016462],
       [ 0.72710197,

In [120]:
np.sum(np.sum(pv_actions * delta, axis=1))

-9.77517884885382e-07

In [130]:
x = np.expand_dims(np.sum(pv_actions, axis=1), axis=1)*delta

In [133]:
x

array([[-3.48109403e-08],
       [-1.27749727e-07],
       [ 4.83878938e-10],
       [ 1.50254233e-08],
       [ 3.32588424e-10],
       [ 1.46857232e-08],
       [-1.15894575e-07],
       [ 0.00000000e+00],
       [-6.53619763e-09],
       [-2.07345849e-08],
       [ 3.97850698e-08],
       [ 1.06892546e-08],
       [-8.31036510e-09],
       [-3.71046105e-08],
       [-1.02123994e-09],
       [ 1.07576835e-07],
       [ 1.25354408e-09],
       [-1.76697426e-08],
       [ 2.08074416e-07],
       [ 2.50261747e-07],
       [-1.21425979e-08],
       [-9.04340509e-09],
       [-1.80168513e-09],
       [ 4.57116847e-09],
       [ 3.71951269e-08],
       [-1.07958552e-07],
       [ 2.47423164e-08],
       [-2.07736608e-08],
       [ 4.08783538e-08],
       [-2.55951623e-08],
       [ 5.94786015e-08],
       [-1.69606607e-07],
       [ 6.07598665e-08],
       [ 7.05728311e-08],
       [-3.59236089e-08],
       [-4.47078646e-07],
       [ 5.31865131e-08],
       [ 2.81829218e-09],
       [-4.6

In [83]:
actions = np.expand_dims(np.repeat(-0.5, 99), axis=1)

In [ ]:
init_pv = 1 # todo randomize per epoch/batch (epoch = 100 steps)
max_leverage = # todo randomize within range

In [86]:
re = actions * delta

In [87]:
re

array([[-1.45e-07],
       [ 7.50e-08],
       [-5.00e-09],
       [-2.00e-08],
       [-1.50e-08],
       [-1.50e-08],
       [ 7.50e-08],
       [-0.00e+00],
       [-4.00e-08],
       [-1.50e-08],
       [ 3.50e-08],
       [-1.50e-08],
       [-2.50e-08],
       [-3.00e-08],
       [-5.00e-09],
       [ 9.00e-08],
       [-9.00e-08],
       [-3.00e-08],
       [-2.60e-07],
       [-3.85e-07],
       [ 2.75e-07],
       [ 1.00e-08],
       [ 1.50e-08],
       [-7.00e-08],
       [ 1.35e-07],
       [-7.00e-08],
       [ 4.50e-08],
       [ 4.00e-08],
       [-4.50e-08],
       [-1.00e-07],
       [-5.00e-08],
       [-1.60e-07],
       [-1.05e-07],
       [ 1.05e-07],
       [-6.00e-08],
       [-4.15e-07],
       [-2.80e-07],
       [ 3.05e-07],
       [ 4.45e-07],
       [ 1.45e-07],
       [-9.50e-08],
       [ 1.75e-07],
       [-3.50e-08],
       [-9.00e-08],
       [ 1.20e-07],
       [-9.50e-08],
       [ 6.00e-08],
       [-1.05e-07],
       [ 6.00e-08],
       [ 1.05e-07],
